development:
  adapter: postgresql
  encoding: unicode
  database: qit_development
  pool: 5
  username: anup

test:
  adapter: postgresql
  encoding: unicode
  database: qit_test
  pool: 5
  username: anup