# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f787c9992ca8aef9b791886dd8a0390d21f51d8b0a7a543d6a40cc466186f22500a3687f57757547b174e8ec8cd19462a86b781a02cd0cf7b6f6f8cb8470e18c

test:
  secret_key_base: 97d369eb094b19becb506adbbc776897677ead9d0580c0f76f50519b66fdceb572e6a45ff8bd22e547b70569dec9e148588615327a43154fb216d142770aeb37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
